import { configureStore } from "@reduxjs/toolkit";
import {
    authSlice,
    cargoSlice,
    departamentoSlice,
    diagnosticoSlice,
    direccionSlice,
    directorSlice,
    empresaSlice,
    equipoSlice,
    sexoSlice,
    soporteSlice,
    tecnicoSlice,
    tipoContratoSlice,
    tipoSolicitudSlice,
    tiposUsuariosSlice,
    uiDirectorSlice,
    uiSoporteSlice,
    uiTecnicoSlice,
    uiUserSlice,
    usersSlice,
} from "../store";

export const store = configureStore({
    reducer: {
        auth: authSlice.reducer,
        users: usersSlice.reducer,
        uiUser: uiUserSlice.reducer,
        tecnico: tecnicoSlice.reducer,
        uiTecnico: uiTecnicoSlice.reducer,
        empresa: empresaSlice.reducer,
        direccion: direccionSlice.reducer,
        director: directorSlice.reducer,
        uiDirector: uiDirectorSlice.reducer,
        departamento: departamentoSlice.reducer,
        sexo: sexoSlice.reducer,
        cargo: cargoSlice.reducer,
        tipoUsuario: tiposUsuariosSlice.reducer,
        tipoContrato: tipoContratoSlice.reducer,
        tipoSolicitud: tipoSolicitudSlice.reducer,
        diagnostico: diagnosticoSlice.reducer,
        equipo: equipoSlice.reducer,
        soporte: soporteSlice.reducer,
        uiSoporte: uiSoporteSlice.reducer,
    },
});
